### ISSUE TITLE
Submit to packagist

### ISSUE THREAD

**Issue by juho-jaakkola** [beck24/embed_extender#11]
I know you're currently using embedly cards for embedding, but for now it's easier for me to just keep using this so I can get my sites upgraded to Elgg 2 asap.

**Comment by juho-jaakkola** [comment]
Bump

**Comment by juho-jaakkola** [comment]
Ping

**Comment by beck24** [comment]
Apparently this has existed all along... since Dec 16 2016 anyway :)

https://packagist.org/packages/beck24/embed_extender
